Update troubleshooting.md, section "Running Puppeteer in Docker"
To preface this pull request, I am very new to web development but found some errors when running the code from the troubleshooting section named "Running Puppeteer in Docker"

In my project I'm using puppeteer to generate PDFs but read about the potential security risk or using the "no-sandbox" option when launching the browser. To avoid this, I added a non-root user with some alterations to the code in the section mentioned above. 

1. The version node:14-slim gives the following error when the image is run
```
Symbol.dispose ??= Symbol('dispose');
               ^^^

SyntaxError: Unexpected token '??='
```
From this answer I learned to update the version of node: https://stackoverflow.com/a/77302476/20609806
I changed my node version to node:slim, but upon further testing an alternative is node:18-slim. Once this has been changed, the following error will occur when you build the image:
```
npm ERR! Tracker "idealTree" already exists
```

I fixed this by adding a WORKDIR of /app as required by Node 15+ from this answer:
https://stackoverflow.com/a/65443098/20609806

```

WORKDIR /app
COPY . . 
... 
// And the respective path changes to transfer ownership to the pptruser
&& chown -R pptruser:pptruser /app \
&& chown -R pptruser:pptruser /home/pptruser \
&& chown -R pptruser:pptruser /app/node_modules \
&& chown -R pptruser:pptruser /app/package.json \
&& chown -R pptruser:pptruser /app/package-lock.json

```

I needed to transfer ownership of /app so that the script could write to the filesystem in Docker.

I then ran the script with an alternate docker run that doesn't require cap-add=SYS_ADMIN or a custom seccomp. 

!! I'm not sure if there are any security problems with this, I was also able to do the same using docker compose !!

```
docker run -i <image_name> node -e "`cat pdf.js`"
```


Finally, in my use case of generating a pdf, I noticed that I could uncomment 
```
ENV PUPPETEER_SKIP_DOWNLOAD true
```
And start the browser without using: executablePath: 'google-chrome-stable'. 
```
const browser = await puppeteer.launch({});
```
It also seemed to work without having the line.

```
CMD ["google-chrome-stable"]
```

For these last two changes, I'm not sure what the reason is for them - so I won't include the alterations in this pull request. Any changes by someone more experienced would be welcomed; I just wanted to share my experience so others could be aware of it.